//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *TrainJob) DeepCopyInto(out *TrainJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TrainJob) DeepCopy() *TrainJob {
	if in == nil {
		return nil
	}
	out := new(TrainJob)
	in.DeepCopyInto(out)
	return out
}

func (in *TrainJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TrainJobList) DeepCopyInto(out *TrainJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrainJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TrainJobList) DeepCopy() *TrainJobList {
	if in == nil {
		return nil
	}
	out := new(TrainJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *TrainJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TrainJobSpec) DeepCopyInto(out *TrainJobSpec) {
	*out = *in
	if in.ModelSpec != nil {
		in, out := &in.ModelSpec, &out.ModelSpec
		*out = new(ModelArchSpec)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Checkpoint.DeepCopyInto(&out.Checkpoint)
	if in.MaxRuntime != nil {
		in, out := &in.MaxRuntime, &out.MaxRuntime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	out.CPUPerNode = in.CPUPerNode.DeepCopy()
	out.MemPerNode = in.MemPerNode.DeepCopy()
	if in.EnableSidecar != nil {
		in, out := &in.EnableSidecar, &out.EnableSidecar
		*out = new(bool)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
}

func (in *TrainJobSpec) DeepCopy() *TrainJobSpec {
	if in == nil {
		return nil
	}
	out := new(TrainJobSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TrainJobStatus) DeepCopyInto(out *TrainJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.LastCheckpointTime != nil {
		in, out := &in.LastCheckpointTime, &out.LastCheckpointTime
		*out = (*in).DeepCopy()
	}
}

func (in *TrainJobStatus) DeepCopy() *TrainJobStatus {
	if in == nil {
		return nil
	}
	out := new(TrainJobStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CheckpointSpec) DeepCopyInto(out *CheckpointSpec) {
	*out = *in
	if in.IntervalMinutes != nil {
		in, out := &in.IntervalMinutes, &out.IntervalMinutes
		*out = new(int32)
		**out = **in
	}
	if in.RetainCount != nil {
		in, out := &in.RetainCount, &out.RetainCount
		*out = new(int32)
		**out = **in
	}
}

func (in *CheckpointSpec) DeepCopy() *CheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelArchSpec) DeepCopy() *ModelArchSpec {
	if in == nil {
		return nil
	}
	out := new(ModelArchSpec)
	*out = *in
	return out
}

func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	*out = *in
	return out
}
